### ISSUE TITLE
"MISSING VALUE" at startup

### ISSUE THREAD

**Issue by cswaters** [rileytwo/darkstudio#10]
Followed instructions for installation on a Mac. Now, when I start RStudio a blank white screen flashes quickly with the message "MISSING VALUE." Then RStudio loads. From what I can tell it works fine after the error message. 

One thing I noticed is that the file browser tab has thick border lines around each item. The screen shots on your `Kiss` theme don't show these.

I'm using the most recent version of RStudio and your `Kiss` theme. 

Nice work BTW.

**Comment by rileytwo** [comment]
Hey @cswaters, thanks for the kind words! I'm glad you are using (and hopefully enjoy) `Kiss` and `daRkStudio`. The screenshots are out of date, and need updating. 

I posted a [workaround](https://github.com/rileytwo/daRkStudio/issues/9#issuecomment-622567421) to stop `MISSING VALUE` from appearing when RStudio starts.

`daRkStudio` is now a package, and can be installed with `remotes` or `devtools`.

```r
remotes::install_github("rileytwo/darkstudio")
darkstudio::install_darkstudio()
```

Can you "undo" the steps in the original installation method, and then try installing the package? Note that you'll need to run `darkstudio::install_darkstudio()` to actually "activate" `daRkStudio`.

**Comment by cswaters** [comment]
Everything works. Looks great. Appreciate the help.

**Comment by rileytwo** [comment]
@cswaters glad to hear it.
