### ISSUE TITLE
Can't activate on macOS Catalina

### ISSUE THREAD

**Issue by clark0x** [rileytwo/darkstudio#17]
```
> darkstudio::activate()
Error: [EACCES] Failed to make directory '/Applications/RStudio.app/Contents/Resources/www/darkstudio': permission denied
```

**Comment by rileytwo** [comment]
A few questions:

1) Are you the only user on the machine you're trying to run this on?
I'm not sure why you would have any permission issues, unless a different user installed RStudio. I've only seen permission errors when making changes to an app that was installed through the App Store.

2) Where is RStudio installed on your system? 

3) Can you run `sessionInfo()` inside RStudio's console, and then paste the results here?

**Comment by clark0x** [comment]
You are right. I do have two user on my mac, and RStudio is installed by a different user. Reinstall RStudio by same user solved. thx~
