### ISSUE TITLE
Rstudio via Anaconda: activation issue

### ISSUE THREAD

**Issue by BirkoRuzicka** [rileytwo/darkstudio#19]
Hi, I'm entirely new to RStudio, so please excuse me if I missed something obvious. I successfully installed the theme using 

`remotes::install_github("rileytwo/darkstudio")`

but cannot activate it. When I enter

`darkstudio::activate()`

I get the following error:
 
"Error in dirname(path) : a character vector argument expected
In addition: Warning message:
In darkstudio::activate() :
  Colors, menus, buttons, and other UI elements of this version of RStudio may not look or function as expected. Please consider updating RStudio to the latest stable version. For the best results, RStudio Preview is recommended."

I find this confusing, as I am sure that I'm running the latest stable version of RStudio (1.1.456). Could this be because I used the Anaconda Navigator to install and run RStudio? I'd be grateful for any help.

**Comment by rileytwo** [comment]
Hey @BirkoRuzicka, no need to apologize. We've all been new at some point! I need a few details in order to help.

1. What OS are you using?
2. What version is your OS? (e.g. macOS 11.3, Windows 10 21H1, etc)
3. Where do you have RStudio installed?
4. Are you the only user on this computer?

**Comment by BirkoRuzicka** [comment]
Hello @rileytwo,
thank you for getting back to me.
I do believe that my issue was caused by Anaconda Navigator, which only allows the older RStudio version 1.1.456 to be installed. I have in the meantime installed RStudio 1.1.1717 without using Anaconda, and it runs smoothly and perfectly. `darkstudio::activate()` was also not a problem anymore.
So if anyone else runs into this problem, they should try that :)
Kind regards!
