### ISSUE TITLE
Cannot be activated on the latest R version

### ISSUE THREAD

**Issue by dreadbalaur** [rileytwo/darkstudio#21]
RStudio version: 2021.09.0+351
R version: 4.1.1
OS: Windows 10 21H1
Ran in admin? Yes

Issue: 
Error encountered when trying to activate using `darkstudio::activate()`

Error message: 
`Error in dirname(path) : a character vector argument expected`

**Comment by rileytwo** [comment]
Are you able to try again with R version 4.1.2? Using 4.1.2, I don't get the error and am able to activate/deactivate successfully.

**Comment by BraINstinct0** [comment]
Same issue still persists on R version 4.2.1, windows, same setting.

**Comment by jmonroynieto** [comment]
I am using R v4.1.2 and I have this same error. MacOS using Rstudio 2022.12.0+353 (2022.12.0+353)

**Comment by rileytwo** [comment]
I think I've figured out the issue for Windows. @BraINstinct0 and @dreadbalaur can you update `darkstudio` and try one more time?

**Comment by neilrq** [comment]
Hi! I really love this package and I found a solution that at least worked for me! =) you see, the troubleshooting says it requires a path, this path is for index.htm and as it says on help page of "darkstudio" package, when you're not setting R Studio installation on default path, like me that I setted on the D:/, you have to provide the access route to your index.htm, highlight on index route and not the directory (understood that looking for the trouble of dir path on Google)... anyways, for me, that I have it on D:/ you must run the following:

darkstudio::activate(path= "D:/Program Files/RStudio/resources/app/www/index.htm")

Hope it fix your problem too and thanks riley for this beautiful package =)

**Comment by MichaelJStein** [comment]
Yes, the same works for me on Mac, R v4.2.2 on RStudio 2022.12.0+353.
Had to define the path to /Applications/RStudio.app/Contents/Resources/app/www/index.htm

Works perfectly, thanks Neil!

**Comment by rileytwo** [comment]
> darkstudio::activate(path= "D:/Program Files/RStudio/resources/app/www/index.htm")
> Hope it fix your problem too and thanks riley for this beautiful package =)

Thanks for posting your solution. Once I find some time I'll update the default paths.

**Comment by Bruno0588** [comment]
> darkstudio::activate(path= "D:/Program Files/RStudio/resources/app/www/index.htm")

Same issue here @rileytwo  Any update will be greatly appreciated (I love this theme!)

Having an issue activating the theme. Windows 11, RStudio 2021.09.0 Build 351 .

**Comment by fmaj0003** [comment]
Hi, Mac user here and using the pathname by @MichaelJStein didn't work for me. RStudio 2023.03.1+446 

Edit: FIXED. For novice RStudio users, this might not be that obvious. When doing darkstudio::activate(), make sure the directory in path = is in speech marks ""

So this is what you should write in console: `darkstudio::activate("/Applications/RStudio.app/Contents/Resources/app/www/index.htm")`

**Comment by rileytwo** [comment]
Hi @fmaj0003, do you mean `darkstudio::activate("/Applications/RStudio.app/Contents/Resources/app/www/index.htm")`? (With quotes?) 

But yes, thanks for posting a solution.

**Comment by rileytwo** [comment]
Seems I didn't have an updated version of RStudio when looking into this issue. The path has been fixed and is working on my mac. Please reopen if anyone is still experiencing the issue.
