### ISSUE TITLE
Styling of operators

### ISSUE THREAD

**Issue by MichaelJStein** [rileytwo/darkstudio#23]
Hi there,

sorry if this is a dumb question but how can I get the operators (<-, ==, <=, etc.) styled as one symbol as in your screenshots? For me it's still displayed the usual way.

Thank you, loving the theme anyways!
Mike 

R version: 4.1.2 
RStudio version: 2022.02.0
OS: macOS 12.3

**Comment by rileytwo** [comment]
Not a dumb question! You'll need a font with ligatures to have operators 'styled as one symbol'. [Fira Code](https://github.com/tonsky/FiraCode) is a popular one. [Here's an article](https://www.andreasrein.net/posts/code-fonts/) with some more options.
