### ISSUE TITLE
Error on new Rstudio version (2022.12.0+353)

### ISSUE THREAD

**Issue by max837381** [rileytwo/darkstudio#27]
When using the dark studio::activate command on MacOS the following error message occurs:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/fs/libs/fs.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/fs/libs/fs.so, 0x0006): Library not loaded: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib
  Referenced from: <91EF0AA1-299C-3A69-B21F-DAA6DD997BCA> /Library/Frameworks/R.framework/Versions/4.2/Resources/library/fs/libs/fs.so
  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache)

**Comment by rileytwo** [comment]
I think this is an issue with your R installation, or at least the installation of some of your packages.

You may want to try reinstalling R. If you do, be sure to reinstall `darkstudio`.
