### ISSUE TITLE
Error with new RStudio version 2022.12.0 - IDE still blue when daRkstudio is activated

### ISSUE THREAD

**Issue by JanecWisniewski** [rileytwo/darkstudio#28]
`darkstudio::activate()` comes back as TRUE but the the theme is still blue (Sky/Modern)

**Comment by mrmorgan17** [comment]
I am having a similar issue as well. I am using version 2022.12.0+353 of RStudio (MacOS) and when I run `darkstudio::activate()` I get the following error:
```
Error in dirname(path) : a character vector argument expected
```

**Comment by JanecWisniewski** [comment]
> I am having a similar issue as well. I am using version 2022.12.0+353 of RStudio (MacOS) and when I run `darkstudio::activate()` I get the following error:
> 
> ```
> Error in dirname(path) : a character vector argument expected
> ```

I had this error message earlier. To fix it, I had to manually add the files darkstudio.css and index.htm to its corresponding directory ("C:\Program Files\RStudio\www" on windows).

**Comment by rileytwo** [comment]
Try updating `darkstudio`. RStudio has a new folder layout on Windows that I was unaware of. I've updated the package to use the new paths. I was able to reproduce the issue myself and am able to run `darkstudio::activate()` successfully.

**Comment by JanecWisniewski** [comment]
> Try updating `darkstudio`. RStudio has a new folder layout on Windows that I was unaware of. I've updated the package to use the new paths. I was able to reproduce the issue myself and am able to run `darkstudio::activate()` successfully.

Awesome! It's fixed now
