### ISSUE TITLE
Where to manually add files on macOS

### ISSUE THREAD

**Issue by mrmorgan17** [rileytwo/darkstudio#29]
> I am having a similar issue as well. I am using version 2022.12.0+353 of RStudio (MacOS) and when I run `darkstudio::activate()` I get the following error:
> 
> ```
> Error in dirname(path) : a character vector argument expected
> ```

I had this error message earlier. To fix it, I had to manually add the files darkstudio.css and index.htm to its corresponding directory ("C:\Program Files\RStudio\www" on windows).

_Originally posted by @JanecWisniewski in https://github.com/rileytwo/darkstudio/issues/28#issuecomment-1359966852_

When I look is this directory on my computer which is running macOS Ventura 13.1, `/Applications/RStudio.app/Contents/Resources` there is no `www` folder. Is that something I need to create or should the `darkstudio.css` and `index.htm` filed be placed elsewhere?

Additionally I'm using RStudio version 2022.12.0-353

**Comment by JanecWisniewski** [comment]
@mrmorgan17 

Yes, try creating the `www` folder and adding both files in that directory.

I just looked on my mac and the `www` folder is indeed under `"~Contents/Resources"` with the `.css` and `.htm` file in it.

**Comment by vishal-singh-r** [comment]
I am facing the same error. I had darkstudio installed previously, but I erased my Mac and reinstalled RStudio. 

My R version is 4.2.2 (2022-10-31)

**Comment by mrmorgan17** [comment]
Ok. I created a `www` folder under `"~Contents/Resources"` and added the `darkstudio.css`  and `index.htm` files to it. When I restarted RStudio, it still looks like it did before, there's a dark background but the borders and the tabs are not dark like they usually are 

Also, when I looked back into the `www` folder, a new `darkstudio` directory had been created under it with another `darkstudio.css` file in it and a `index.htm.pre-ds` file

**Comment by vishal-singh-r** [comment]
@mrmorgan17 

Do you mean after adding the www folder and the files, you are still seeing bluish borders or are they dark grey like they are supposed to be (if darkstudio functioned properly)? 

I tried the method you suggested; yet, I am still seeing the bluish tone in the borders - meaning darkstudio had no effect.

I can run RStudio without the www folder in Resources, perhaps, as mentioned in #28 comment, the path in MacOS has also changed like in Windows?

**Comment by mrmorgan17** [comment]
@TopBottomTau I'm still seeing bluish borders is what I mean

**Comment by JanecWisniewski** [comment]
@mrmorgan17 

Sorry if this is a stupid question, but did you try running `darkstudio::activate()` in your console on RStudio after adding the new files? 

Also, the new `darkstudio` directory in the `www` folder is a normal occurrence.

**Comment by mrmorgan17** [comment]
No worries about the question, I appreciate the help. I did run `dark studio::activate()` in my console and it returned `TRUE`. I also restarted RStudio to see if it would take effect after that but I didn't see any changes with that either

**Comment by JanecWisniewski** [comment]
And I assume you've already tried to update the package as well?

**Comment by mrmorgan17** [comment]
I assume so, I manually downloaded the package from GitHub today and used the `.css` and `.htm` files from that download. Says its version 0.2.0

**Comment by vishal-singh-r** [comment]
I should mention that when I delete the www folder and run `activate()`, it gives the following error:

`Error in dirname(path) : a character vector argument expected`

and when I add the dark studio files, it gives the following warning:

`[1] TRUE
Warning message:
In index$modified(file_index) :
  index.htm is already modified. Not modifying.`

and when run again (as darkstudio created its folder), it gives the following:

`Error in index$backup(path = path_index) : 
  A backup index file already exists. Run darkstudio::deactivate() and retry darkstudio::activate().` 

Restarting RStudio at any step does not change the theme. Even after using `deactivate()` and `darkstudio::activate()` again.

**Comment by grcatlin** [comment]
@mrmorgan17 @TopBottomTau the file path for the index.htm did change recently and is now found at `/Applications/RStudio.app/Contents/Resources/app/www/index.htm`. 

If you want to get this working manually, you'll have to navigate to that file and edit it such that it links the darkstudio.css in question. You can just place darkstudio.css in the existing www folder and add this line to the index.htm:

`<link type=\"text/css\" rel=\"stylesheet\" href=\"darkstudio.css\" />`

If that's too much work, I finished a project inspired by darkstudio that will allow a similar functionality and should run on RStudio 2022.12.0+353 on MacOS which you can find [here](https://github.com/grcatlin/rs.ui).

As per the last comment, you may need to completely reinstall RStudio if it's looping like that.

**Comment by mrmorgan17** [comment]
@sotha-lit's fork worked for me. Still had trouble with this one even following the advice of @grcatlin.
