### ISSUE TITLE
Makes Little/No Changes in 1.2.1256

### ISSUE THREAD

**Issue by evelynswarton** [rileytwo/darkstudio#3]
In the latest preview of RStudio, bringing the .htm and .css files do not make the program appear darker. Reading the latest release notes it seems as though the following may play a role: 
An upgraded rendering engine based on Chromium, which improves performance and visual quality.
It is also possible that I have not installed it correctly.
![issue](https://user-images.githubusercontent.com/47308228/52185154-25f56c80-27d1-11e9-8e94-4a343bf4fb57.jpg)

**Comment by rileytwo** [comment]
Thanks for making an issue.

I've noticed that with each release update, some of the properties in custom_styles.css are renamed/changed. I'm not sure what the reasoning for this is, and I'm not aware of any changes I can make in custom_styles.css to prevent the update from causing issues. I've recently updated Rstudio v1.2.1268 and had similar problems. I'll push the changes in a moment.

**Comment by rileytwo** [comment]
Still having troubles, @felipe-finesse?

**Comment by evelynswarton** [comment]
No troubles. Works great now, thanks!
