### ISSUE TITLE
Error when activating darkstudio on Mac

### ISSUE THREAD

**Issue by andyhouldcroft** [rileytwo/darkstudio#33]
Hi, 

I am trying to setup darkstudio on Mac, but when trying to use
`darkstudio::activate()`
I receive the following error message
`Error in dirname(path) : a character vector argument expected`

Is this an issue with elevated privileges as you mentioned in the installation steps?

Cheers,
Andy

**Comment by sinaryan** [comment]
I have the same issue on the m1 MacBook

**Comment by rileytwo** [comment]
Duplicate of #21
