### ISSUE TITLE
fix to dialog box when importing from readr

### ISSUE THREAD

**Issue by aassumpcao** [rileytwo/darkstudio#4]
Hi Riley,

I first wanted to thank you for the great theme. I have installed it last week and it looks great! Second, I wanted to report an issue I'm still seeing on the readr import dialog box. I'm working off version 1.2.1326, just fyi.

This is what I have: 
![Screen Shot 2019-03-20 at 9 26 55 AM](https://user-images.githubusercontent.com/36233632/54689702-6ea18480-4af6-11e9-9734-fd2dd3575a90.png)

I have done some digging and found out that the style reference for such box is .GD15MCFCOID (and children, of course), which I believe was not configured in your original custom_style.css file. This is what I have done to mine and how it looks like right now.

```
.GD15MCFCOID {
  color: #ffffff;
  padding-top: 3px;
  padding-left: 3px;
  padding-right: 3px;
  padding-bottom: 3px;
}
```
![Screen Shot 2019-03-20 at 10 08 04 AM](https://user-images.githubusercontent.com/36233632/54690640-34d17d80-4af8-11e9-8e08-1be209f1578a.png)

I know it's not looking perfect and might conflict with other settings but I just wanted to share this with you if you see anything similar on your end.

Lastly, I would suggest updating the readme.md on this repository. I was confused about whether I should use the custom_styles.css from `daRkStudio-master/` or from the `daRkStudio-master/daRkStudio/` folder. They are distinct files so perhaps some clarification would be good.

Regardless, great work and thanks for sharing this!

Andre

**Comment by rileytwo** [comment]
Hi Andre, thanks for your feedback! I was updating some items in the repo when I noticed `custom_styles.css` and `index.htm` under `daRkStudio-master/daRkstudio`. I'm not sure how I missed that.

I like the work you've done on . GD15MCFCOID in the readr input-file dialogue. That peice has been tricky to keep on top of. There have been times when I've updated RStudio and property names/classes have changed, which caused things to break. .GD15MCFCOID is one of those.

After looking at the object, I wasn't able to make it look the same as yours, although I made an attempt to fix the property. I'm using RStudio Version 1.2.1335, and the property .GD15MCFCOID hasn't changed names, so I think the fix should work for you, if you decide to try it.

<img width="1264" alt="Screen Shot 2019-03-30 at 8 32 43 AM" src="https://user-images.githubusercontent.com/34988536/55276856-a5318900-52c6-11e9-996d-a20901a9af44.png">

My main issue was handling the padding, as I wasn't able to find a way to create borders similar to the ones in your example (which I like, btw).

I just made a push that fixes the dialogue. If you try it out, let me know if it works!

**Comment by aassumpcao** [comment]
> I just made a push that fixes the dialogue. If you try it out, let me know if it works!

Thanks for this, Riley. I will take a look at how this looks like in my version of RStudio and I will let you know. I have not had the time to do this yet, so I apologize for the delay.

**Comment by aassumpcao** [comment]
Hi Riley,

I have finally checked this and this is what is different in my css file. I guess I had more styles than I had originally reported, and I apologize for not seeing this before. You can pick and choose (or replace) these lines in your file and you should see the padding work.

```
/* dialog box diff */
.GD15MCFCNID {
  border: 1px solid #0a0a0a;
  background-color: #323232;
  color: #ffffff;
  padding-top: 10px;
  padding-left: 4px;
  padding-bottom: 3px;
  margin-top: 3px;
  margin-right: 5px;
  margin-left: 5px;
}

.GD15MCFCOID {
  color: #ffffff;
  height: 107px;
  margin: 3px 3px 3px 3px;
  padding-top: 2px;
  padding-left: 2px;
  padding-right: 2px;
  padding-bottom: 2px;
}

.GD15MCFCPID {
  border: 1px solid #ffffff;
  background-color: #323232;
  color: #ffffff;
}
```

Additionally, I noticed the console bar has a different color on your new template. See below what I see when I fire up RStudio.

![console bar](https://user-images.githubusercontent.com/36233632/55735937-584d6100-59f0-11e9-8fa0-d5d00bdffdb9.png)

If you would like, I changed mine to the following color scheme using these two styles:

![Screen Shot 2019-04-08 at 11 23 12 AM](https://user-images.githubusercontent.com/36233632/55736148-c003ac00-59f0-11e9-89de-6df980e0f6f8.png)

```
/* console diff */
.rstudio-themes-flat .rstudio-themes-dark-grey .GD15MCFCKV.GD15MCFCPO {
  border-color: rgb(0, 0, 0);
}

.rstudio-themes-flat .rstudio-themes-dark-grey .GD15MCFCKV.GD15MCFCPO div.GD15MCFCMO .GD15MCFCIS {
  background: rgb(50, 50, 50);
  border-color: rgb(0, 0, 0);
}
```
Again, thank you. This looks great!

Andre

**Comment by rileytwo** [comment]
No worries! It's really easy to not notice some of the rules for the myriad of elements in the file. I'm not sure what the cause is/was, but my console didn't have the blue background like you showed. I'm glad you were able to find a fix though 😄.
