### ISSUE TITLE
Manu bar still blue under Windows 10

### ISSUE THREAD

**Issue by frederikziebell** [rileytwo/darkstudio#8]
Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/28304028/66190925-6e7d6680-e68d-11e9-82ee-f86340017897.png)

**Comment by rileytwo** [comment]
So, from what I can tell, RStudio's menu bar is outside the scope of what's customizable through injecting css into `index.htm`. The menu bar and editors (the four panes) are built using different frameworks; Qt is used for the menu bar, while Ace is used for the editors.

However, someone else has made a package that solves this problem! Check out [rscodeio](https://github.com/anthonynorth/rscodeio) and let me know if this is what you expected the menu bar to look like.

**Comment by frederikziebell** [comment]
This works as I was hoping, thanks a lot!

**Comment by rileytwo** [comment]
No problem! Since the menu bar isn't within the scope of this project, I'm going to close this issue. I'm open to reopening the issue if anyone feels that styling the menu should be included here, or if anyone wants to open a PR.
